services:
  app:
    build: .  # Build context is the current directory
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.env
    command: python /app/scripts/controller.py
