from datetime import datetime

image_table = {
        'id': str,
        'origin_id': (str, type(None)),
        'wp_id': (int, type(None)),
        'url': (str, type(None)),
        'wp_url': (str, type(None)),
        'query': (str, type(None)),
        'photographer': (str, type(None)),
        'dimensions': (str, type(None)),
        'post_id': (int, type(None)),
        'provider': (str, type(None)),
        'is_featured_media': (bool, type(None)),
        'photographer_url': (str, type(None)),
        'type': (str, type(None)),
        'description': (str, type(None)),
        'topic_id': (int, type(None)),
        'file_name': (str, type(None)),
        'width': (int, type(None)),
        'height': (int, type(None)),
        'alt_text': (str, type(None)),
        'alt_image_urls': (list, type(None)),
    }

post_table = {
        'id': int,
        'date': (datetime, type(None)),
        'date_gmt': (datetime, type(None)),
        'guid': (str, type(None)),
        'link': (str, type(None)),
        'modified': (datetime, type(None)),
        'modified_gmt': (datetime, type(None)),
        'slug': (str, type(None)),
        'status': str,
        'type': (str, type(None)),
        'password': (str, type(None)),
        'permalink_template': (str, type(None)),
        'generated_slug': (str, type(None)),
        'title': str,
        'content': str,
        'author': (int, type(None)),
        'excerpt': (str, type(None)),
        'featured_media': (int, type(None)),
        'comment_status': str,
        'ping_status': str,
        'format': str,
        'meta': (dict, type(None)),
        'sticky': (bool, type(None)),
        'template': (str, type(None)),
        'categories': (list, type(None)),
        'tags': (list, type(None)),
        'topic_id': (int, type(None)),
        'date_created': (datetime, type(None)),
        'image_queries': (list, type(None)),
        'yoast_meta': (dict, type(None))
    }

wp_post_table = {
    'date' : datetime,
    'date_gmt' : datetime,
    'title' : str,
    'content' : str,
    'excerpt' : str,
    'categories' : list,
    'tags' : list,
    'featured_media' : int,
    'status' : str,
    'slug' : str,
    'format' : str,
    'sticky' : bool,
    'template' : str,
    'meta' : dict,
    'author' : int,
    'password' : str,
    'type' : str,
    'comment_status' : str,
    'ping_status' : str,
    'generated_slug' : str,
    'link' : str,
    'guid' : str,
    'modified' : datetime,
    'modified_gmt' : datetime,
    'yoast_meta' : dict,
}