name: Scheduled Python Workflow

on:
  schedule:
    - cron: '0 9,17 * * *'
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: jakekinchen/cybernewsaggregator:latest
      
      - name: Run Docker image
        uses: addnab/docker-run-action@v3
        with:
          image: jakekinchen/cybernewsaggregator:latest # Ensure this matches the tag used above and is all lowercase
          options: -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
