name: Scheduled Python Workflow

on:
  schedule:
    - cron: '0 9,17 * * *'
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      
      # Login to Docker Hub (if needed for pushing image or private base images)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build Docker Image
      - name: Build Docker image
        run: docker build -t my-app .

      # Run Docker Container
      - name: Run Docker container
        run: |
          docker run \
            -v ${{ github.workspace }}:/app \
            -v /var/run/docker.sock:/var/run/docker.sock \
            --env-file .env \
            --name my-app-container \
            my-app python /app/scripts/init.py